### PR TITLE
Trace library changed to standard logging module

### PR DESCRIPTION
**Pull request by ogle650**

### CODE REVIEW

**Comment by jhofstee** [comment]
Logging works fine for localsettings afaik and I can not find a single motivation in your patches to change it. Why do you want to change it?

**Comment by ogle650** [comment]
Because tracing.setupTraces was not working for me...
tracing.setupTraces(tracingEnabled, pathTraces, traceFileName, traceToConsole, traceToFile, traceDebugOn)

**Comment by mpvader** [comment]
Hey both, let me help a bit; I've been wondering about that tracing module as well; years ago:

tracing.py is something made by ourselves a long time ago. The top says this:
```
## IMPORTANT NOTE - MVA 2015-2-5 
# This file is  deprecated. Use the standard logging package of Python instead
```
https://github.com/victronenergy/velib_python/blob/2d390a2d7dd6bca5d28d83a040d705f099a156d6/tracing.py#L2

**Comment by ogle650** [comment]
Ok thanks for your help :-)

**Comment by mpvader** [comment]
Hi; I'm not sure why you're closing it? What you did in your commits is getting rid of an old package that is not to be used anymore.

**Comment by ogle650** [comment]
I pulled it because I have seen in the header file that tracing was deprecated and also I was not aware of velib_python, I tried to correct it. I didn't try but even if it's deprecated, velib_python should permits to execute localsettings. Don't understand why it's deprecated because it already used tracing library.

**Comment by mpvader** [comment]
Hi, I think me not being a native English speaker; and perhaps you too(?) is causing some miscommunication here.

Anyway: I very much like your work to get rid of the tracing module.

I do have some comments before we can accept this PR. I'd like to strip it down to a bare minimum of functionality; to be in line with our other projects. dbus-systemcalc is a good example; [see line 880](https://github.com/victronenergy/dbus-systemcalc-py/blob/master/dbus_systemcalc.py#L880). It uses our [logger class](https://github.com/victronenergy/velib_python/blame/master/logger.py); basically a simple bootstrapper for the native Python logging module.

Making this change would include removing the `to file` and `to console` options. It would be always to stdout and stderr; and anyone that wants it in a file (such as ourselves in Venus OS) would need to use standard piping for that.

Also please re-organize the commits so that they are just one; or if necessary perhaps two. Ie. no more `Update README.md` commits.

ok?

**Comment by jhofstee** [comment]
localsettings is using standard logging now

**Pull request closed without merging**
